apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../../the_project

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: todo-broadcaster-dep
    path: broadcaster-log-mode.yaml
  - path: disable-db-backup.yaml
