alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  remoteWrite: []

# Static scrape config for NATS metrics
extraScrapeConfigs: |
  - job_name: nats
    metrics_path: /metrics
    static_configs:
      - targets:
          - my-nats-0.my-nats-headless.nats.svc.cluster.local:7777
