apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres-ss
spec:
  serviceName: todo-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"      # Allows bursts for heavy queries
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi