apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: project
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:aEuUSSiP1mBVrQ==,iv:aL0pxiqgqpB7x8vK8gDK8mWOnUVBNeIk6t7tTlj9KR0=,tag:ZKZIqodGn+ACx+v/A5Um/A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vpZDZkl2Fec=,iv:qA8O5W0UWbd6aHnj6tPNwl/IHONmcgrYrH32/boys7I=,tag:r8p2LtpEpGdiQ1HxM4uYyg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PxN5tJlSteHk0MbsG+I=,iv:r93sHey0g5zZZIfjMwd+vgIE4Zyg1WgLoIHMaE2SDag=,tag:CY8TJq08yTfHjid58z3qHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN0RmdUE2VnFZM2FFMVhJ
            VFRrSktzSEcyNGJVZmZ4bW51bkxZZUxUTlhNCmJhVEw4dVVtTlVUT3drQVg0NThz
            aWxLS0NGTnRCd2lWcGtIMS9GbWVlZm8KLS0tIEhrNENpcTRvUWYzN1NXVXlNanpz
            OW4zRGw2aFhvbkVWQ3cyS3FuQ0tnNE0K4NTy36bGd6tI1PDw2glxT5/R2AgTQ03M
            BvwBhM+9ZpOpgQp8P2SSwXNDTYG65TsRSceNMPVXZ5cweIg4HQTeTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156a929qc2hg6svc3lcu5hnxs06e55a53fhvhf5znswswhtn5kyrs8mv0g7
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-06T23:31:38Z"
    mac: ENC[AES256_GCM,data:YS894H0PeubIGxCxhsY2Ut1SOuI03ECGQ2pPRBBc3PYoLX0hHOYMCTBpsXAuUjOtlUBCY4BkFvxjSDti5cuyhM89/0RnT/6o+jO48k2/L1bKjmuMNy3h9XhR0P7+8Cp40gV7zka9H0hJYXH/PM94GJn7f3dScdnGyxVXBQtdm9o=,iv:GDZX6M0nSqWayddeIDwXlTrww/dp3c0Lv4+pcQ5OG8o=,tag:fqojwKYX4viZ0+q1vYdvxA==,type:str]
    version: 3.13.3
