apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config

data:
  PORT: "8000"
  BACKEND_URL: "http://todo-backend-svc:8000"
  IMAGE_DIR: "/app/images"
  CACHE_DURATION: "600"
  IMAGE_SOURCE_URL: "https://picsum.photos/1200"